[package]
name = "B_Auth_1_backend"
version = "0.1.0"
edition = "2018"

[dependencies]
ic-cdk = "0.15.0"
ic-cdk-macros = "0.15.0"
candid = "0.10.10"
serde = { version = "1.0", features = ["derive"] }
serde_cbor = "0.11"
serde_json = "1.0"

[lib]
crate-type = ["cdylib"]
